## 异常处理
### 同步错误处理
- 常规函数的错误可以使用try-catch捕获。
- 生成器函数的错误可以使用try-catch处理。
### 异步错误处理
#### 定时器的错误处理
- setTimeout外层加try-catch无法捕获错误。
```
try {
  setTimeout(() => {
    throw Error("error");
  }, 1000);
} catch (error) {
  console.error(error.message);
}
```
- setTimeout回调函数中加try-catch可以捕获错误。
```
setTimeout(() => {
  try {
    throw Error("error");
  } catch (error) {
    console.error(error.message);
  }
}, 1000);
```
#### 事件的错误处理
- 事件处理外层加try-catch无法捕获错误。
```
const button = document.querySelector("button");
try {
  button.addEventListener("click", function() {
    throw Error("error");
  });
} catch (error) {
  console.error(error.message);
}
```
- 事件处理回调函数中加try-catch可以捕获错误。
```
const button = document.querySelector("button");
button.addEventListener("click", function() {
  try {
    throw Error("error");
  } catch (error) {
    console.error(error.message);
  }
});
```
#### onerror
- 当img标签或script等HTML元素命中不存在的资源时，onerror事件处理程序就会触发。
```
const image = document.querySelector("img");
image.addEventListener("error", function(event) {
  console.log(event);
});
```
#### Promise的错误处理
- 使用catch方法处理被拒绝的Promise或Promise中的异常。
```
new Promise((resolve, reject) => {
  return reject(Error("error"));
})
.then(res => console.log('res'))
.catch(error => console.log('error'))  // 'error'

new Promise((resolve, reject) => {
  throw Error("error");
})
.then(res => console.log('res'))
.catch(error => console.log('error')) // 'error'
```
- 使用catch方法处理Promise.all、Promise.any、Promise.race、Promise.allSettled中的异常。
#### async/await的错误处理
- 使用try-catch处理async/await的错误。
```
const a = async() => {
  throw Error("error");
  return 'a';
}

const b = async() => {
  try {
    const res = await a();
    console.log(res);
  } catch (error) {
    console.log('error'); // 'error'
  }
}
b();
```
- 使用Promise.catch处理。
> 使用Promise.catch处理相较于try-catch处理可以继续执行await后续的代码，可以通过判断await执行的返回值判断是否继续执行后续代码。

```
const a = async() => {
  throw Error("error");
  return 'a';
}

const b = async() => {
  const res = await a().catch((error) => console.log('error')); // 'error'
  console.log(res); // undefined
  if (!res) return;
}
b();
```
- 使用await-to-js插件处理。
#### 异步生成器函数的错误可以使用try-catch处理。
